### ISSUE TITLE
Wrong screens pop up after change date V0.36

### ISSUE THREAD

**Issue by MikeChermin** [WaalbrugWire/Roster-Planner#13]
Reproduction malfunction:
1. Start v036.jar
2. Click Edit
3. Change date ( i.e. 2018-06-01 to 2018-06-02)
4. Click OK
5. Click on OK popped up "Dates changed." screen
Result: Pop up message "Removed 0 old off requests);"
6. Click OK
       Results in similar screen "Removed 1 old....
7. Repetition clicks on OK similar screens
       Results in pop screens up to Removed 7 old.. )

Remark: click on cancel  "Dates changed." screen shows no unnecessary pop ups.

Version v0.36, no data set necessary.

**Comment by Cranium1** [comment]
@BR50Kab Solved this issue earlier this week
