### ISSUE TITLE
Print issues Roster (Optaplanner) V0.35  version

### ISSUE THREAD

**Issue by MikeChermin** [WaalbrugWire/Roster-Planner#8]
Mac OSX El Capitan 10.11.6: Printing tested for v0.35; CWZ8_Rules testset delivers: png, and jpeg files after after terminating solving. They are put in "....data\nurserostering\export map related to Roster (opta)planner. No excel output observed.

Similar for Windows10 printing result in a Print event error message: javax imageio IOException. Can't create an ImageOutputStream! Further clicking shows more messages. For example Document created in data\nurserostering\export map.

In both cases the fysical printer is offline.

**Comment by Cranium1** [comment]
CSV bug fixed in v0.36 (both windows and mac)
