### ISSUE TITLE
Malfunction: Export, save functions  (to  .xml) Windows 10 V0.35 Roster(opta)planner

### ISSUE THREAD

**Issue by MikeChermin** [WaalbrugWire/Roster-Planner#9]
**Export, save functie (to .xml) at Windows10 computer:** 

-> Rosterplanner message: "Uncaught exception" Thread "AWT-EventQueue-0" java lang illegalArgumentException Could not writethe file  ...xml.

**Comment by Cranium1** [comment]
Finally figured out the solution for the export/print errors before solving, will be fully implemented tomorrow

**Comment by Cranium1** [comment]
Just committed solution
